/* Dom Quixote: progressive enhancement. No content is generated by motion. */
(() => {
  'use strict';
  const reduce = matchMedia('(prefers-reduced-motion: reduce)');
  const header = document.querySelector('[data-header]');
  const menuButton = document.querySelector('.menu-toggle');
  const mobileNav = document.querySelector('#mobile-nav');
  const form = document.querySelector('#booking-form');
  const gs = window.gsap;
  let lenis = null;
  let menuTween = null;
  let opening = false;
  let menuVersion = 0;
  let scrollFrame = 0;
  const blocked = [...document.querySelectorAll('main,.site-footer,.whatsapp-float')];
  const updateHeader = () => {
    header?.classList.toggle('is-scrolled', scrollY > 30);
    scrollFrame = 0;
  };
  addEventListener('scroll', () => {
    if (!scrollFrame) scrollFrame = requestAnimationFrame(updateHeader);
  }, { passive: true });
  updateHeader();

  function setMenu(open, returnFocus = true, instantly = false) {
    if (!menuButton || !mobileNav) return;
    opening = open;
    const version = ++menuVersion;
    menuTween?.kill();
    menuButton.setAttribute('aria-expanded', String(open));
    menuButton.querySelector('b').textContent = open ? 'Fechar menu' : 'Abrir menu';
    const finish = () => {
      if (version !== menuVersion) return;
      if (!open) {
        mobileNav.hidden = true;
        document.body.classList.remove('menu-open');
        blocked.forEach(el => { el.inert = false; });
        lenis?.start();
        if (returnFocus) menuButton.focus({ preventScroll: true });
      }
      if (gs) gs.set([mobileNav, ...mobileNav.children], { clearProps: 'opacity,transform,clipPath' });
    };
    if (open) {
      mobileNav.hidden = false;
      document.body.classList.add('menu-open');
      blocked.forEach(el => { el.inert = true; });
      lenis?.stop();
      if (!reduce.matches && gs && !instantly) {
        menuTween = gs.timeline({ onComplete: finish });
        menuTween.fromTo(mobileNav, { clipPath: 'inset(0 0 100% 0 round 0 0 36px 36px)' }, { clipPath: 'inset(0 0 0% 0 round 0px)', duration: .65, ease: 'power4.inOut' })
          .fromTo(mobileNav.children, { y: 30, opacity: 0 }, { y: 0, opacity: 1, stagger: .065, duration: .6, ease: 'power3.out' }, .22);
      } else finish();
      mobileNav.querySelector('a')?.focus({ preventScroll: true });
    } else if (!reduce.matches && gs && !instantly) {
      menuTween = gs.to(mobileNav, { opacity: 0, y: -12, duration: .25, onComplete: finish });
    } else finish();
  }
  menuButton?.addEventListener('click', () => setMenu(!opening));
  mobileNav?.querySelectorAll('a').forEach(link => link.addEventListener('click', () => setMenu(false, true, true)));
  document.addEventListener('keydown', event => {
    if (!opening) return;
    if (event.key === 'Escape') { event.preventDefault(); setMenu(false); }
    if (event.key === 'Tab') {
      const list = [menuButton, ...mobileNav.querySelectorAll('a')];
      const index = list.indexOf(document.activeElement);
      if (event.shiftKey && index <= 0) { event.preventDefault(); list.at(-1).focus(); }
      else if (!event.shiftKey && (index === list.length - 1 || index === -1)) { event.preventDefault(); menuButton.focus(); }
    }
  });
  matchMedia('(min-width: 961px)').addEventListener('change', event => {
    if (event.matches && opening) setMenu(false, false, true);
  });
  reduce.addEventListener('change', () => { if (opening) setMenu(true, false, true); });

  // Local dates: avoid UTC shifting the minimum day near midnight.
  if (form) {
    const checkin = form.elements.checkin;
    const checkout = form.elements.checkout;
    const status = form.querySelector('.form-status');
    const localISO = date => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;
    const tomorrow = value => { const date = new Date(`${value}T12:00:00`); date.setDate(date.getDate() + 1); return localISO(date); };
    const today = localISO(new Date());
    checkin.min = today;
    checkout.min = tomorrow(today);
    function validateDates() {
      checkin.min = localISO(new Date());
      checkout.min = tomorrow(checkin.value || checkin.min);
      checkout.setCustomValidity(checkin.value && checkout.value && checkout.value <= checkin.value ? 'Preencha as datas para consultar a disponibilidade.' : '');
    }
    checkin.addEventListener('change', () => {
      if (checkout.value && checkout.value <= checkin.value) checkout.value = '';
      validateDates(); status.textContent = '';
    });
    checkout.addEventListener('input', validateDates);
    form.addEventListener('invalid', () => { status.textContent = 'Preencha as datas para consultar a disponibilidade.'; }, true);
    form.addEventListener('submit', event => {
      event.preventDefault();
      validateDates();
      if (!form.checkValidity()) {
        status.textContent = 'Preencha as datas para consultar a disponibilidade.';
        form.reportValidity(); return;
      }
      const inDate = new Date(`${checkin.value}T12:00:00`).toLocaleDateString('pt-BR');
      const outDate = new Date(`${checkout.value}T12:00:00`).toLocaleDateString('pt-BR');
      const message = `Olá, gostaria de consultar a disponibilidade no Hotel Dom Quixote. Check-in: ${inDate}. Check-out: ${outDate}. Acomodação: ${form.elements.room.value}.`;
      status.textContent = 'Abrindo o WhatsApp da recepção…';
      const destination = `https://wa.me/5521969480023?text=${encodeURIComponent(message)}`;
      // Same-tab navigation avoids popup blockers; no reservation is confirmed here.
      window.location.assign(destination);
    });
  }

  // Accessible native details with cancellable height transitions.
  document.querySelectorAll('.faq-list details').forEach(detail => {
    let animation;
    let expanded = detail.open;
    detail.querySelector('summary').addEventListener('click', event => {
      if (reduce.matches || !detail.animate) return;
      event.preventDefault();
      const from = detail.getBoundingClientRect().height;
      animation?.cancel();
      expanded = !expanded;
      detail.style.height = '';
      detail.open = true;
      const to = expanded ? detail.getBoundingClientRect().height : detail.querySelector('summary').getBoundingClientRect().height + 1;
      detail.style.overflow = 'hidden';
      animation = detail.animate({ height: [`${from}px`, `${to}px`] }, { duration: 380, easing: 'cubic-bezier(.16,1,.3,1)' });
      animation.onfinish = () => { detail.open = expanded; detail.style.overflow = ''; detail.style.height = ''; window.ScrollTrigger?.refresh(); lenis?.resize(); };
    });
    reduce.addEventListener('change', () => { animation?.cancel(); detail.open = expanded; detail.style.overflow = ''; detail.style.height = ''; });
  });

  // Follow internal anchors with native fallback and proper focus handling.
  document.querySelectorAll('a[href^="#"]').forEach(anchor => {
    anchor.addEventListener('click', event => {
      const id = anchor.getAttribute('href');
      const target = id.length > 1 ? document.getElementById(id.slice(1)) : null;
      if (!target || !lenis || reduce.matches) return;
      event.preventDefault();
      if (opening) setMenu(false, false, true);
      lenis.scrollTo(target, { offset: -100, duration: 1.1, onComplete: () => {
        history.pushState(null, '', id);
        if (!target.hasAttribute('tabindex')) { target.setAttribute('tabindex', '-1'); target.addEventListener('blur', () => target.removeAttribute('tabindex'), { once: true }); }
        target.focus({ preventScroll: true });
      }});
    });
  });

  if (!gs || !window.ScrollTrigger) return; // Visible HTML and native scroll survive.
  gs.registerPlugin(window.ScrollTrigger);
  const mm = gs.matchMedia();
  mm.add('(prefers-reduced-motion: no-preference)', () => {
    let ticker;
    const listeners = [];
    const add = (target, name, fn) => { target.addEventListener(name, fn); listeners.push(() => target.removeEventListener(name, fn)); };
    if (window.Lenis) {
      lenis = new window.Lenis({ duration: 1.05, smoothWheel: true, syncTouch: false, autoRaf: false, anchors: false, prevent: node => Boolean(node.closest?.('.mobile-nav,.hero-gallery,input,select')) });
      lenis.on('scroll', window.ScrollTrigger.update);
      ticker = time => lenis?.raf(time * 1000);
      gs.ticker.add(ticker);
      if (opening) lenis.stop();
    }
    const hero = document.querySelector('.hero');
    if (hero && scrollY < 150) {
      gs.timeline({ defaults: { ease: 'power3.out' } })
        .from('.hero-copy .eyebrow', { y: 16, opacity: 0, duration: .65 })
        .from('.hero h1', { y: 48, opacity: 0, duration: 1.05 }, .08)
        .from('.hero-lede,.hero-actions', { y: 20, opacity: 0, duration: .8, stagger: .1 }, .33)
        .from('.hero-gallery', { clipPath: 'inset(12% 3% 0 3% round 40px)', duration: 1.3 }, .26)
        .from('.hero-gallery img', { scale: 1.13, duration: 1.5 }, .28);
    }
    document.querySelectorAll('main>section:not(.hero)').forEach(section => {
      const items = [...section.querySelectorAll('h2,.eyebrow,.section-index,.section-heading>p,.split-copy>p:not(.eyebrow),.room-card,.review-card,.proof-item,.amenity-list li,.faq-list details,.booking-form,.trust-strip>div')];
      if (section.matches('.trust-strip')) items.push(...section.children);
      // Stagger starts only when visible; nothing is left hidden below fold.
      window.ScrollTrigger.create({ trigger: section, start: 'top 88%', once: true, onEnter: () => {
        gs.from(items, { y: 24, opacity: 0, duration: .85, stagger: .065, ease: 'power3.out', clearProps: 'opacity,transform' });
        const images = section.querySelectorAll('.editorial-image,.amenities-image,.location-visual');
        gs.from(images, { clipPath: 'inset(0 0 18% 0 round 32px)', duration: 1.1, ease: 'power3.out', clearProps: 'clipPath' });
      }});
    });
    const fine = matchMedia('(hover:hover) and (pointer:fine)').matches;
    if (fine) {
      document.querySelectorAll('.button,.circle-link').forEach(button => {
        let frame = 0;
        const move = event => {
          cancelAnimationFrame(frame);
          const rect = button.getBoundingClientRect();
          const x = Math.max(-7, Math.min(7, (event.clientX - rect.left - rect.width / 2) * .12));
          const y = Math.max(-5, Math.min(5, (event.clientY - rect.top - rect.height / 2) * .14));
          frame = requestAnimationFrame(() => { button.style.setProperty('--mx', `${x}px`); button.style.setProperty('--my', `${y}px`); });
        };
        const reset = () => { cancelAnimationFrame(frame); button.style.removeProperty('--mx'); button.style.removeProperty('--my'); };
        add(button, 'pointermove', move); add(button, 'pointerleave', reset); add(button, 'blur', reset); listeners.push(reset);
      });
      document.querySelectorAll('.room-card').forEach(card => {
        let frame = 0;
        const move = event => {
          cancelAnimationFrame(frame);
          const rect = card.getBoundingClientRect();
          const x = (event.clientX - rect.left) / rect.width - .5;
          const y = (event.clientY - rect.top) / rect.height - .5;
          frame = requestAnimationFrame(() => { card.style.setProperty('--rx', `${-y * 7}deg`); card.style.setProperty('--ry', `${x * 9}deg`); });
        };
        const reset = () => { cancelAnimationFrame(frame); card.style.removeProperty('--rx'); card.style.removeProperty('--ry'); };
        const reveal = () => { gs.fromTo(card.querySelector('.room-info p'), { clipPath: 'inset(0 100% 0 0)' }, { clipPath: 'inset(0 0% 0 0)', duration: .55, ease: 'power3.out', clearProps: 'clipPath', overwrite: true }); };
        add(card, 'pointermove', move); add(card, 'pointerleave', reset); add(card, 'pointerenter', reveal); add(card, 'focusin', reveal); listeners.push(reset);
      });
    }
    document.querySelectorAll('.editorial-image img,.amenities-image img,.location-visual img,.hero-main img').forEach(image => {
      image.classList.add('parallax-image');
      gs.fromTo(image, { yPercent: -3, scale: 1.075 }, { yPercent: 3, scale: 1.075, ease: 'none', scrollTrigger: { trigger: image.parentElement, start: 'top bottom', end: 'bottom top', scrub: .8 } });
    });
    const refresh = () => { window.ScrollTrigger.refresh(); lenis?.resize(); };
    document.fonts?.ready.then(refresh);
    add(window, 'load', refresh);
    return () => {
      listeners.forEach(remove => remove());
      if (ticker) gs.ticker.remove(ticker);
      lenis?.destroy(); lenis = null;
      document.querySelectorAll('.parallax-image').forEach(image => image.classList.remove('parallax-image'));
    };
  });
})();
